name: ci

on: [push, pull_request]

jobs:
  check:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repo
        uses: actions/checkout@v4

      - name: Set Node v18
        uses: actions/setup-node@v4
        with:
          node-version: 18
          cache: 'npm'

      - name: Set npm version
        run: npm i -g npm@8

      - name: Install dependencies
        run: npm ci

      - name: Build source code
        run: npm run dist
